version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "npm"
    directory: "/landing-site"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "npm"
    directory: "/apps/phile-tool"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
